service: kartmax-nuxt-dummy-site
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: ap-south-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

package:
  individually: true
  exclude:
    - node_modules/**
    - components/**
    - layouts/**
    - middleware/**
    - pages/**
    - plugins/**
    - store/**
    - .github/**
    - .idea/**
    - .eslintrc.js
    - package-lock.json

  include:
    - dist/**
    - .htaccess
    - nuxt.config.js
    - binaryMimeTypes.js
    - nuxt.js
    - index.js
    - .env

functions:
  nuxt:
    handler: index.nuxt
    events:
      - httpApi: '*'
    layers:
      - arn:aws:lambda:ap-south-1:531458784015:layer:sagar-chauhan-aws-lambda-layer-nodejs-nuxt-installation:9

plugins:
  - serverless-apigw-binary
  - serverless-offline

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'
